services:
  dbeducation:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    networks:
      - education

  adminereducation:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - dbeducation
    networks:
      - education

networks:
  education:
    driver: bridge
